In [113]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies_cleaned.csv')
movies

,id,title,year,duration,MPA,rating,votes,meta_score,description,writers,...,budget,opening_weekend_gross,gross_worldwide,gross_us_canada,countries_origin,production_companies,awards_content,genres,languages,tagged_description
0,tt0083866,E.T. the Extra-Terrestrial,1982,1h 55m,PG,7.9,452K,92.0,A troubled child summons the courage to help a...,Melissa Mathison,...,"$10,500,000 (estimated)","$11,835,389","$797,307,407","$439,454,989",United States,"Universal Pictures, Amblin Entertainment","Won 4 Oscars, 52 wins & 38 nominations total","Coming-of-Age, Space Sci-Fi, Adventure, Family...",English,tt0083866 A troubled child summons the courage...
1,tt0084805,Tootsie,1982,1h 56m,PG,7.4,118K,88.0,"Michael Dorsey, an unsuccessful actor, disguis...","Don McGuire, Larry Gelbart, Murray Schisgal",...,"$21,000,000 (estimated)","$5,540,470","$177,200,285","$177,200,000",United States,"Columbia Pictures, Mirage Enterprises, Punch P...","Won 1 Oscar, 26 wins & 31 nominations total","Farce, High-Concept Comedy, Romantic Comedy, C...",English,"tt0084805 Michael Dorsey, an unsuccessful acto..."
2,tt0084434,An Officer and a Gentleman,1982,2h 4m,R,7.1,65K,75.0,A young man must complete his work at a Navy O...,Douglas Day Stewart,...,"$7,500,000 (estimated)","$3,304,679","$129,795,890","$129,795,554",United States,"Lorimar Film Entertainment, Paramount Pictures","Won 2 Oscars, 9 wins & 15 nominations total","Feel-Good Romance, Drama, Romance","English, Filipino",tt0084434 A young man must complete his work a...
3,tt0084602,Rocky III,1982,1h 39m,PG,6.8,219K,57.0,Rocky faces the ultimate challenge from a powe...,Sylvester Stallone,...,"$17,000,000 (estimated)","$12,431,486","$125,052,898","$125,049,125",United States,"Chartoff-Winkler Productions, United Artists","Nominated for 1 Oscar, 3 wins & 9 nominations ...","Boxing, Drama, Sport",English,tt0084602 Rocky faces the ultimate challenge f...
4,tt0084726,Star Trek II: The Wrath of Khan,1982,1h 53m,PG,7.7,132K,68.0,"With the assistance of the Enterprise crew, Ad...","Gene Roddenberry, Jack B. Sowards, Harve Bennett",...,"$11,200,000 (estimated)","$14,347,221","$79,822,604","$79,707,906",United States,Paramount Pictures,"Awards, 4 wins & 9 nominations total","Space Sci-Fi, Action, Adventure, Sci-Fi",English,tt0084726 With the assistance of the Enterpris...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14052,tt0093593,On the Silver Globe,1988,2h 46m,Unrated,7.2,5.3K,72.0,A team of astronauts land on an inhabitable pl...,"Andrzej Zulawski, Jerzy Zulawski",...,NaN,NaN,$557,NaN,Poland,"Zespol Filmowy ""Kadr""","Awards, 1 nomination total","Space Sci-Fi, Adventure, Drama, Fantasy, Sci-Fi",Polish,tt0093593 A team of astronauts land on an inha...
14053,tt0095444,Killer Klowns from Outer Space,1988,1h 28m,PG-13,6.2,49K,43.0,Aliens who look like clowns come from outer sp...,"Charles Chiodo, Stephen Chiodo, Edward Chiodo",...,"$2,000,000 (estimated)",NaN,"$1,412",NaN,United States,"Sarlui / Diamant, Chiodo Brothers Productions","Awards, 2 nominations total","Alien Invasion, B-Horror, Dark Comedy, Monster...",English,tt0095444 Aliens who look like clowns come fro...
14054,tt0094793,Brain Damage,1988,1h 24m,R,6.5,14K,61.0,"One morning, a young man wakes to find that a ...",Frank Henenlotter,...,"$900,000 (estimated)",NaN,NaN,NaN,United States,Palisades Partners,"Awards, 1 nomination total","Body Horror, Dark Comedy, Comedy, Horror",English,"tt0094793 One morning, a young man wakes to fi..."
14055,tt0095403,Police Story 2,1988,1h 41m,PG-13,7.1,24K,68.0,The Hong Kong supercop must stop a group of bl...,"Jackie Chan, Paul B. Clay, Edward Tang",...,NaN,NaN,NaN,NaN,Hong Kong,"Golden Harvest Company, Golden Way Films Ltd.,...","Awards, 2 wins & 1 nomination total","Dark Comedy, Martial Arts, Slapstick, Action, ...",Cantonese,tt0095403 The Hong Kong supercop must stop a g...
14056,tt0096218,Tales from the Gimli Hospital,1988,1h 12m,Unrated,6.6,1.5K,71.0,While their mother is dying in the modern Giml...,Guy Maddin,...,"$25,000 (estimated)",NaN,NaN,NaN,Canada,"Extra Large Productions, The Canada Manitoba C...","Awards, 1 nomination total","Dark Comedy, Comedy, Drama, Fantasy, Horror, T...","Icelandic, English",tt0096218 While their mother is dying in the m...

In [114]:
all_genres = movies['genres'].str.split(',').explode()
genre_counts = all_genres.str.strip().value_counts().sort_values(ascending=False).reset_index()

genre_counts = pd.DataFrame(genre_counts)
print(genre_counts['genres'].unique())

['Drama' 'Comedy' 'Thriller' 'Romance' 'Action' 'Crime' 'Documentary'
 'Adventure' 'Mystery' 'Horror' 'Biography' 'Fantasy' 'Sci-Fi'
 'Dark Comedy' 'Family' 'History' 'Music' 'Period Drama' 'War' 'Animation'
 'Sport' 'Satire' 'Romantic Comedy' 'Psychological Thriller' 'Tragedy'
 'Slapstick' 'Supernatural Horror' 'Coming-of-Age' 'Psychological Drama'
 'Docudrama' 'Musical' 'Superhero' 'Computer Animation' 'True Crime'
 'Parody' 'Slasher Horror' 'Buddy Comedy' 'Animal Adventure' 'Teen Comedy'
 'Teen Drama' 'Dark Fantasy' 'Western' 'Quest' 'Epic'
 'Psychological Horror' 'Supernatural Fantasy' 'Space Sci-Fi'
 'One-Person Army Action' 'Feel-Good Romance' 'Teen Horror' 'Road Trip'
 'Suspense Mystery' 'Martial Arts' 'Quirky Comedy' 'Action Epic'
 'High-Concept Comedy' 'Adventure Epic' 'Whodunnit' 'Survival'
 'Dystopian Sci-Fi' 'Anime' 'Hand-Drawn Animation' 'Farce'
 'Urban Adventure' 'Spy' 'Body Horror' 'Serial Killer' 'Raunchy Comedy'
 'Alien Invasion' 'Teen Romance' 'Holiday' 'Caper' 'Political Thriller'
 'Adult Animation' 'Conspiracy Thriller' 'Sci-Fi Epic' 'Monster Horror'
 'Fairy Tale' 'Zombie Horror' 'Political Drama' 'Splatter Horror'
 'Fantasy Epic' 'Workplace Drama' 'Showbiz Drama' 'Teen Adventure'
 'Steamy Romance' 'Dark Romance' 'Gangster' 'Cyberpunk' 'Erotic Thriller'
 'Time Travel' 'Costume Drama' 'Tragic Romance' 'Jungle Adventure'
 'Buddy Cop' 'Vampire Horror' 'Globetrotting Adventure' 'Sword & Sorcery'
 'Holiday Comedy' 'Disaster' 'Artificial Intelligence' 'Heist' 'War Epic'
 'Found Footage Horror' 'Swashbuckler' 'Teen Fantasy' 'Police Procedural'
 'Legal Drama' 'Sea Adventure' 'Pop Musical' 'News' 'B-Horror'
 'Cyber Thriller' 'Folk Horror' 'Cop Drama' 'Sports Documentary'
 'Drug Crime' 'Car Action' 'Desert Adventure' 'Music Documentary'
 'Prison Drama' 'Gun Fu' 'Legal Thriller' 'Basketball'
 'Contemporary Western' 'Historical Epic' 'Football'
 'Stop Motion Animation' 'Romantic Epic' 'Kaiju' 'Stoner Comedy'
 'Steampunk' 'Sword & Sandal' 'Mountain Adventure' 'Dinosaur Adventure'
 'Boxing' 'Jukebox Musical' 'Extreme Sport' 'Nature Documentary'
 'Crime Documentary' 'Baseball' 'Political Documentary' 'Holiday Family'
 'Body Swap Comedy' 'Holiday Romance' 'Food Documentary' 'Kung Fu'
 'Financial Drama' 'Faith & Spirituality Documentary' 'Screwball Comedy'
 'Science & Technology Documentary' 'Mockumentary' 'Motorsport'
 'Witch Horror' 'B-Action' 'Military Documentary' 'Water Sport'
 'Werewolf Horror' 'Bumbling Detective' 'Concert' 'Medical Drama'
 'Stand-Up' 'Western Epic' 'Wuxia' 'History Documentary' 'Soccer'
 'Rock Musical' 'Cozy Mystery' 'Hard-boiled Detective' 'Giallo' 'Samurai'
 'Travel Documentary' 'Iyashikei' 'Shōnen' 'Holiday Animation'
 'Slice of Life' 'Sketch Comedy' 'Mecha' 'Shōjo' 'Korean Drama' 'Seinen'
 'Isekai' 'Josei' 'Sitcom' 'Classic Musical' 'Talk Show' 'Game Show'
 'Classical Western']

In [115]:
genre_mapping = {'Drama': ('Period Drama', 'Psychological Drama', 'Docudrama', 'Teen Drama', 'Political Drama', 'Workplace Drama', 'Showbiz Drama',
                           'Costume Drama', 'Legal Drama', 'Cop Drama', 'Korean Drama', 'Prison Drama', 'Financial Drama', 'Medical Drama', 'Drama', 
                           'Police Procedural'),
                'Comedy': ('Dark Comedy', 'Satire', 'Romantic Comedy', 'Slapstick', 'Buddy Comedy', 'Teen Comedy', 'Quirky Comedy', 'High-Concept Comedy',
                           'Raunchy Comedy', 'Stoner Comedy', 'Body Swap Comedy', 'Stand-Up', 'Sitcom', 'Screwball Comedy', 'Comedy', 'Farce'),
                'Thriller': ('Psychological Thriller', 'Political Thriller', 'Erotic Thriller', 'Cyber Thriller', 'Legal Thriller', 'Thriller', 'Conspiracy Thriller',
                             'Disaster', 'Giallo', 'Survival'),
                'Romance': ('Feel-Good Romance', 'Teen Romance', 'Steamy Romance', 'Dark Romance', 'Tragic Romance', 'Holiday Romance', 'Romantic Epic', 'Romance',
                            'Shōjo'),
                'Action': ('Action', 'War', 'Superhero', 'One-Person Army Action', 'Martial Arts', 'Action Epic', 'Spy', 'Car Action', 'Gun Fu', 'B-Action', 
                           'Samurai', 'Kaiju', 'Mecha'), 
                'Documentary': ('Sports Documentary', 'Music Documentary', 'Crime Documentary', 'Nature Documentary', 'Political Documentary', 'Food Documentary', 
                                'Faith & Spirituality Documentary', 'Science & Technology Documentary', 'Mockumentary', 'Military Documentary', 'History Documentary', 
                                'Travel Documentary', 'Documentary', 'Biography', 'True Crime', 'News', 'Sports Documentary', 'History'), 
                'Adventure': ('Adventure', 'Animal Adventure', 'Western', 'Quest', 'Epic', 'Road Trip', 'Adventure Epic', 'Urban Adventure', 'Teen Adventure', 
                              'Time Travel', 'Jungle Adventure', 'Globetrotting Adventure', 'War Epic', 'Swashbuckler', 'Sea Adventure', 'Desert Adventure',
                              'Contemporary Western', 'Historical Epic', 'Steampunk', 'Sword & Sandal', 'Mountain Adventure', 'Dinosaur Adventure', 'Western Epic',
                              'Wuxia', 'Seinen', 'Isekai', 'Classical Western'),
                'Mystery': ('Mystery', 'Suspense Mystery', 'Whodunnit', 'Bumbling Detective', 'Cozy Mystery', 'Hard-boiled Detective'), 
                'Horror': ('Horror', 'Supernatural Horror', 'Slasher Horror', 'Psychological Horror', 'Teen Horror', 'Body Horror', 'Serial Killer', 'Monster Horror', 
                           'Zombie Horror', 'Splatter Horror', 'Vampire Horror', 'Found Footage Horror', 'B-Horror', 'Folk Horror', 'Witch Horror', 'Werewolf Horror'), 
                'Fantasy': ('Fantasy', 'Dark Fantasy', 'Supernatural Fantasy', 'Fairy Tale', 'Fantasy Epic', 'Sword & Sorcery', 'Teen Fantasy'), 
                'Crime': ('Crime', 'Caper', 'Gangster', 'Heist', 'Drug Crime'), 
                'Sci-Fi': ('Sci-Fi', 'Space Sci-Fi', 'Dystopian Sci-Fi', 'Alien Invasion', 'Sci-Fi Epic', 'Cyberpunk', 'Artificial Intelligence'), 
                'Sport': ('Sport', 'Basketball', 'Football', 'Boxing', 'Extreme Sport', 'Baseball', 'Motorsport', 'Water Sport', 'Soccer'), 
                'Family': ('Family', 'Holiday', 'Holiday Family', 'Iyashikei', 'Shōnen', 'Slice of Life'),
                'Musical': ('Music', 'Musical', 'Pop Musical', 'Jukebox Musical', 'Concert', 'Rock Musical', 'Classic Musical'),
                'Animation': ('Animation', 'Anime', 'Computer Animation', 'Hand-Drawn Animation', 'Adult Animation', 'Stop Motion Animation', 'Holiday Animation')}

In [116]:
subgenre_to_category = {}
for category, subgenres in genre_mapping.items():
    for sub in subgenres:
        subgenre_to_category[sub] = category

def map_to_main_genres(genre_str):
    if pd.isna(genre_str):
        return []
    matched_genres = set()
    for genre in [g.strip() for g in genre_str.split(',')]:
        if genre in subgenre_to_category:
            matched_genres.add(subgenre_to_category[genre])
    return list(matched_genres)

movies['simple_genres'] = movies['genres'].apply(map_to_main_genres)
movies

,id,title,year,duration,MPA,rating,votes,meta_score,description,writers,...,opening_weekend_gross,gross_worldwide,gross_us_canada,countries_origin,production_companies,awards_content,genres,languages,tagged_description,simple_genres
0,tt0083866,E.T. the Extra-Terrestrial,1982,1h 55m,PG,7.9,452K,92.0,A troubled child summons the courage to help a...,Melissa Mathison,...,"$11,835,389","$797,307,407","$439,454,989",United States,"Universal Pictures, Amblin Entertainment","Won 4 Oscars, 52 wins & 38 nominations total","Coming-of-Age, Space Sci-Fi, Adventure, Family...",English,tt0083866 A troubled child summons the courage...,"[Adventure, Family, Sci-Fi]"
1,tt0084805,Tootsie,1982,1h 56m,PG,7.4,118K,88.0,"Michael Dorsey, an unsuccessful actor, disguis...","Don McGuire, Larry Gelbart, Murray Schisgal",...,"$5,540,470","$177,200,285","$177,200,000",United States,"Columbia Pictures, Mirage Enterprises, Punch P...","Won 1 Oscar, 26 wins & 31 nominations total","Farce, High-Concept Comedy, Romantic Comedy, C...",English,"tt0084805 Michael Dorsey, an unsuccessful acto...","[Romance, Comedy, Drama]"
2,tt0084434,An Officer and a Gentleman,1982,2h 4m,R,7.1,65K,75.0,A young man must complete his work at a Navy O...,Douglas Day Stewart,...,"$3,304,679","$129,795,890","$129,795,554",United States,"Lorimar Film Entertainment, Paramount Pictures","Won 2 Oscars, 9 wins & 15 nominations total","Feel-Good Romance, Drama, Romance","English, Filipino",tt0084434 A young man must complete his work a...,"[Romance, Drama]"
3,tt0084602,Rocky III,1982,1h 39m,PG,6.8,219K,57.0,Rocky faces the ultimate challenge from a powe...,Sylvester Stallone,...,"$12,431,486","$125,052,898","$125,049,125",United States,"Chartoff-Winkler Productions, United Artists","Nominated for 1 Oscar, 3 wins & 9 nominations ...","Boxing, Drama, Sport",English,tt0084602 Rocky faces the ultimate challenge f...,"[Drama, Sport]"
4,tt0084726,Star Trek II: The Wrath of Khan,1982,1h 53m,PG,7.7,132K,68.0,"With the assistance of the Enterprise crew, Ad...","Gene Roddenberry, Jack B. Sowards, Harve Bennett",...,"$14,347,221","$79,822,604","$79,707,906",United States,Paramount Pictures,"Awards, 4 wins & 9 nominations total","Space Sci-Fi, Action, Adventure, Sci-Fi",English,tt0084726 With the assistance of the Enterpris...,"[Adventure, Action, Sci-Fi]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14052,tt0093593,On the Silver Globe,1988,2h 46m,Unrated,7.2,5.3K,72.0,A team of astronauts land on an inhabitable pl...,"Andrzej Zulawski, Jerzy Zulawski",...,NaN,$557,NaN,Poland,"Zespol Filmowy ""Kadr""","Awards, 1 nomination total","Space Sci-Fi, Adventure, Drama, Fantasy, Sci-Fi",Polish,tt0093593 A team of astronauts land on an inha...,"[Fantasy, Adventure, Drama, Sci-Fi]"
14053,tt0095444,Killer Klowns from Outer Space,1988,1h 28m,PG-13,6.2,49K,43.0,Aliens who look like clowns come from outer sp...,"Charles Chiodo, Stephen Chiodo, Edward Chiodo",...,NaN,"$1,412",NaN,United States,"Sarlui / Diamant, Chiodo Brothers Productions","Awards, 2 nominations total","Alien Invasion, B-Horror, Dark Comedy, Monster...",English,tt0095444 Aliens who look like clowns come fro...,"[Horror, Comedy, Sci-Fi]"
14054,tt0094793,Brain Damage,1988,1h 24m,R,6.5,14K,61.0,"One morning, a young man wakes to find that a ...",Frank Henenlotter,...,NaN,NaN,NaN,United States,Palisades Partners,"Awards, 1 nomination total","Body Horror, Dark Comedy, Comedy, Horror",English,"tt0094793 One morning, a young man wakes to fi...","[Horror, Comedy]"
14055,tt0095403,Police Story 2,1988,1h 41m,PG-13,7.1,24K,68.0,The Hong Kong supercop must stop a group of bl...,"Jackie Chan, Paul B. Clay, Edward Tang",...,NaN,NaN,NaN,Hong Kong,"Golden Harvest Company, Golden Way Films Ltd.,...","Awards, 2 wins & 1 nomination total","Dark Comedy, Martial Arts, Slapstick, Action, ...",Cantonese,tt0095403 The Hong Kong supercop must stop a g...,"[Thriller, Comedy, Action, Crime]"
14056,tt0096218,Tales from the Gimli Hospital,1988,1h 12m,Unrated,6.6,1.5K,71.0,While their mother is dying in the modern Giml...,Guy Maddin,...,NaN,NaN,NaN,Canada,"Extra Large Productions, The Canada Manitoba C...","Awards, 1 nomination total","Dark Comedy, Comedy, Drama, Fantasy, Horror, T...","Icelandic, English",tt0096218 While their mother is dying in the m...,"[Thriller, Comedy, Drama, Fantasy, Horror]"

In [117]:
movies[~(movies['simple_genres'].isna())]

,id,title,year,duration,MPA,rating,votes,meta_score,description,writers,...,opening_weekend_gross,gross_worldwide,gross_us_canada,countries_origin,production_companies,awards_content,genres,languages,tagged_description,simple_genres
0,tt0083866,E.T. the Extra-Terrestrial,1982,1h 55m,PG,7.9,452K,92.0,A troubled child summons the courage to help a...,Melissa Mathison,...,"$11,835,389","$797,307,407","$439,454,989",United States,"Universal Pictures, Amblin Entertainment","Won 4 Oscars, 52 wins & 38 nominations total","Coming-of-Age, Space Sci-Fi, Adventure, Family...",English,tt0083866 A troubled child summons the courage...,"[Adventure, Family, Sci-Fi]"
1,tt0084805,Tootsie,1982,1h 56m,PG,7.4,118K,88.0,"Michael Dorsey, an unsuccessful actor, disguis...","Don McGuire, Larry Gelbart, Murray Schisgal",...,"$5,540,470","$177,200,285","$177,200,000",United States,"Columbia Pictures, Mirage Enterprises, Punch P...","Won 1 Oscar, 26 wins & 31 nominations total","Farce, High-Concept Comedy, Romantic Comedy, C...",English,"tt0084805 Michael Dorsey, an unsuccessful acto...","[Romance, Comedy, Drama]"
2,tt0084434,An Officer and a Gentleman,1982,2h 4m,R,7.1,65K,75.0,A young man must complete his work at a Navy O...,Douglas Day Stewart,...,"$3,304,679","$129,795,890","$129,795,554",United States,"Lorimar Film Entertainment, Paramount Pictures","Won 2 Oscars, 9 wins & 15 nominations total","Feel-Good Romance, Drama, Romance","English, Filipino",tt0084434 A young man must complete his work a...,"[Romance, Drama]"
3,tt0084602,Rocky III,1982,1h 39m,PG,6.8,219K,57.0,Rocky faces the ultimate challenge from a powe...,Sylvester Stallone,...,"$12,431,486","$125,052,898","$125,049,125",United States,"Chartoff-Winkler Productions, United Artists","Nominated for 1 Oscar, 3 wins & 9 nominations ...","Boxing, Drama, Sport",English,tt0084602 Rocky faces the ultimate challenge f...,"[Drama, Sport]"
4,tt0084726,Star Trek II: The Wrath of Khan,1982,1h 53m,PG,7.7,132K,68.0,"With the assistance of the Enterprise crew, Ad...","Gene Roddenberry, Jack B. Sowards, Harve Bennett",...,"$14,347,221","$79,822,604","$79,707,906",United States,Paramount Pictures,"Awards, 4 wins & 9 nominations total","Space Sci-Fi, Action, Adventure, Sci-Fi",English,tt0084726 With the assistance of the Enterpris...,"[Adventure, Action, Sci-Fi]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14052,tt0093593,On the Silver Globe,1988,2h 46m,Unrated,7.2,5.3K,72.0,A team of astronauts land on an inhabitable pl...,"Andrzej Zulawski, Jerzy Zulawski",...,NaN,$557,NaN,Poland,"Zespol Filmowy ""Kadr""","Awards, 1 nomination total","Space Sci-Fi, Adventure, Drama, Fantasy, Sci-Fi",Polish,tt0093593 A team of astronauts land on an inha...,"[Fantasy, Adventure, Drama, Sci-Fi]"
14053,tt0095444,Killer Klowns from Outer Space,1988,1h 28m,PG-13,6.2,49K,43.0,Aliens who look like clowns come from outer sp...,"Charles Chiodo, Stephen Chiodo, Edward Chiodo",...,NaN,"$1,412",NaN,United States,"Sarlui / Diamant, Chiodo Brothers Productions","Awards, 2 nominations total","Alien Invasion, B-Horror, Dark Comedy, Monster...",English,tt0095444 Aliens who look like clowns come fro...,"[Horror, Comedy, Sci-Fi]"
14054,tt0094793,Brain Damage,1988,1h 24m,R,6.5,14K,61.0,"One morning, a young man wakes to find that a ...",Frank Henenlotter,...,NaN,NaN,NaN,United States,Palisades Partners,"Awards, 1 nomination total","Body Horror, Dark Comedy, Comedy, Horror",English,"tt0094793 One morning, a young man wakes to fi...","[Horror, Comedy]"
14055,tt0095403,Police Story 2,1988,1h 41m,PG-13,7.1,24K,68.0,The Hong Kong supercop must stop a group of bl...,"Jackie Chan, Paul B. Clay, Edward Tang",...,NaN,NaN,NaN,Hong Kong,"Golden Harvest Company, Golden Way Films Ltd.,...","Awards, 2 wins & 1 nomination total","Dark Comedy, Martial Arts, Slapstick, Action, ...",Cantonese,tt0095403 The Hong Kong supercop must stop a g...,"[Thriller, Comedy, Action, Crime]"
14056,tt0096218,Tales from the Gimli Hospital,1988,1h 12m,Unrated,6.6,1.5K,71.0,While their mother is dying in the modern Giml...,Guy Maddin,...,NaN,NaN,NaN,Canada,"Extra Large Productions, The Canada Manitoba C...","Awards, 1 nomination total","Dark Comedy, Comedy, Drama, Fantasy, Horror, T...","Icelandic, English",tt0096218 While their mother is dying in the m...,"[Thriller, Comedy, Drama, Fantasy, Horror]"

In [118]:
from transformers import pipeline

genres = ['Drama', 'Comedy', 'Thriller', 'Romance', 'Action', 'Documentary', 'Adventure', 'Mystery', 'Horror', 'Fantasy', 'Crime', 'Sci-Fi', 
          'Sport', 'Family', 'Musical', 'Animation']

pipe = pipeline('zero-shot-classification', model='facebook/bart-large-mnli')

Device set to use mps:0

In [119]:
sequence = movies.loc[0, 'description']
result = pipe(sequence, genres, multi_label=True)
print(result)

{'sequence': 'A troubled child summons the courage to help a friendly alien escape from Earth and return to his home planet.', 'labels': ['Adventure', 'Action', 'Animation', 'Sci-Fi', 'Drama', 'Fantasy', 'Mystery', 'Documentary', 'Romance', 'Family', 'Comedy', 'Thriller', 'Musical', 'Crime', 'Sport', 'Horror'], 'scores': [0.8667860627174377, 0.8546441197395325, 0.6773840188980103, 0.6031626462936401, 0.4025791585445404, 0.32712748646736145, 0.21665333211421967, 0.2015196532011032, 0.17122586071491241, 0.14793150126934052, 0.1242089569568634, 0.08676888048648834, 0.036052946001291275, 0.012445931322872639, 0.006345884408801794, 0.0020119021646678448]}

In [120]:
max_index = np.argmax(result['scores'])
max_label = result['labels'][max_index]
max_label

'Adventure'

In [121]:
def generate_predictions(sequence, genres):
    predictions = pipe(sequence, genres, multi_label=True)
    max_index = np.argmax(predictions['scores'])
    max_label = predictions['labels'][max_index]
    return max_label

In [122]:
from tqdm import tqdm

actual_genres = []
predicted_genres = []

for i in tqdm(range(0, 300)):
    sequence = movies.loc[i, 'description']
    predicted_genres += [generate_predictions(sequence, genres)]

for i in range(0, 300):
    actual = movies.loc[i, 'simple_genres']
    actual_genres.append(actual)

100%|██████████| 300/300 [01:47<00:00,  2.79it/s]

In [126]:
predictions_df = pd.DataFrame({'actual_genres': actual_genres, 'predicted_genres': predicted_genres})
predictions_df.head(25)

                               actual_genres predicted_genres
0                [Adventure, Family, Sci-Fi]        Adventure
1                   [Romance, Comedy, Drama]           Comedy
2                           [Romance, Drama]           Action
3                             [Drama, Sport]            Drama
4                [Adventure, Action, Sci-Fi]           Sci-Fi
5   [Thriller, Comedy, Drama, Crime, Action]            Crime
6                         [Thriller, Horror]           Family
7                          [Musical, Comedy]            Drama
8           [Musical, Comedy, Drama, Family]        Adventure
9                                    [Drama]           Action
10           [Adventure, Documentary, Drama]      Documentary
11     [Family, Adventure, Thriller, Action]            Drama
12                                  [Comedy]           Horror
13             [Adventure, Thriller, Action]           Sci-Fi
14              [Fantasy, Adventure, Family]        Adventure
15                      [Adventure, Fantasy]           Action
16      [Adventure, Fantasy, Horror, Action]        Adventure
17                  [Romance, Comedy, Drama]           Family
18                        [Thriller, Horror]           Horror
19               [Adventure, Action, Sci-Fi]        Adventure
20         [Thriller, Drama, Action, Sci-Fi]           Sci-Fi
21                          [Romance, Drama]           Family
22                           [Comedy, Drama]           Family
23                [Musical, Comedy, Romance]          Musical
24                          [Comedy, Sci-Fi]            Drama

In [128]:
movies[['title', 'description', 'simple_genres']].head(25)

,title,description,simple_genres
0,E.T. the Extra-Terrestrial,A troubled child summons the courage to help a...,"[Adventure, Family, Sci-Fi]"
1,Tootsie,"Michael Dorsey, an unsuccessful actor, disguis...","[Romance, Comedy, Drama]"
2,An Officer and a Gentleman,A young man must complete his work at a Navy O...,"[Romance, Drama]"
3,Rocky III,Rocky faces the ultimate challenge from a powe...,"[Drama, Sport]"
4,Star Trek II: The Wrath of Khan,"With the assistance of the Enterprise crew, Ad...","[Adventure, Action, Sci-Fi]"
5,48 Hrs.,A hard-nosed cop reluctantly teams up with a w...,"[Thriller, Comedy, Drama, Crime, Action]"
6,Poltergeist,A family's home becomes the center of paranorm...,"[Thriller, Horror]"
7,The Best Little Whorehouse in Texas,A town's Sheriff and regular patron of a histo...,"[Musical, Comedy]"
8,Annie,A spunky young orphan is taken in by a rich ec...,"[Musical, Comedy, Drama, Family]"
9,The Verdict,"An outcast, alcoholic Boston lawyer sees the c...",[Drama]
10,Gandhi,The life of the lawyer who became the famed le...,"[Adventure, Documentary, Drama]"
11,First Blood,A veteran Green Beret is forced by a cruel She...,"[Family, Adventure, Thriller, Action]"
12,The Toy,An underemployed reporter finds himself litera...,[Comedy]
13,Firefox,A retired air force pilot is sent into the Sov...,"[Adventure, Thriller, Action]"
14,The Dark Crystal,"On another planet in the distant past, a Gelfl...","[Fantasy, Adventure, Family]"
15,Conan the Barbarian,A powerful warrior seeks to avenge the genocid...,"[Adventure, Fantasy]"
16,The Sword and the Sorcerer,A mercenary with a three-bladed sword rediscov...,"[Adventure, Fantasy, Horror, Action]"
17,Best Friends,After five successful years of living and work...,"[Romance, Comedy, Drama]"
18,Friday the 13th: Part 3,Jason Voorhees stalks a group of friends who h...,"[Thriller, Horror]"
19,Tron,A computer hacker is abducted into the digital...,"[Adventure, Action, Sci-Fi]"
20,Blade Runner,A blade runner must pursue and terminate four ...,"[Thriller, Drama, Action, Sci-Fi]"
21,Sophie's Choice,Sophie is the survivor of Nazi concentration c...,"[Romance, Drama]"
22,The World According to Garp,A struggling young writer finds his life and w...,"[Comedy, Drama]"
23,Victor/Victoria,A struggling female soprano in 1934 Paris fina...,"[Musical, Comedy, Romance]"
24,Airplane II: The Sequel,A computer glitch causes a passenger space shu...,"[Comedy, Sci-Fi]"